# Thymeleaf模板引擎
spring:
  profiles:
    active: jdbc
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: true

    # Redis NoSQL数据库
  redis:
    # Redis数据库索引，默认为0
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis密码，默认为空
    password:
    # Redis连接池最大连接数(负值表示没有限制
    jedis:
      pool:
        max-active: 10
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池最大空闲链接
        max-idle: 10
        # 连接池最小空闲链接
        min-idle: 0
    # 链接超时使劲
    timeout: 0

  jpa:
        database: mysql
        show-sql: true
        hibernate:
        # update 第一次加载model自动建立起表的结构
        # create 每次加载删除重建表
        # create-drop 每次加载生成表，sessionFactory关闭，表自动删除
        # validate 验证表结构，不会创建表，会插入新的值
          ddl-auto: update
          naming:
          # 遇到大写字母加 "_" 命名法
          # org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          # 无修改命名法
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
           hibernate:
              dialect: org.hibernate.dialect.MySQL5Dialect

# Mybatis映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hly.sirius.domain

# 端口设置
server:
  port: 8080



